### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by focalinteractive** [elleracompany/craft-cookie-consent#10]
Hello! Is it possible to localise the content displayed in the cookie consent dialog?

**Comment by jellingsen** [comment]
Hi!

Localization of dialog would be up to the developer. The plugin is multi-site compatible so one site for each language would be the recommended approach as per [the docs](https://docs.craftcms.com/v3/localization.html).

All text that is displayed on elements like buttons are translatable by creating a file called cookie-consent.php in the translations/your_lang/ directory. You can use [cookie-consent.php](https://github.com/elleracompany/craft-cookie-consent/blob/master/src/translations/en/cookie-consent.php) as a template.

I hope this answered your question. If you have any further questions please direct them to support@ellera.no so that we can use github issues for tracking bugs and features.
