### ISSUE TITLE
Compatible with FastCGI Cache

### ISSUE THREAD

**Issue by paragonn** [elleracompany/craft-cookie-consent#30]
Hi!

We recently purchased your plugin and we really like it. 

However, we are using FastCGI Cache and are having difficulty getting the cookie consent popup to play nice with the cached pages. The popup appears, but when the user clicks on "Save" or "Ok", the cookie-consent cookie is not created. 

Do you have any recommendations regarding configuration with FastCGI Cache? 

Thanks!

Cheers,
Shannon

**Comment by paragonn** [comment]
Nevermind, we figured it out. You can use a SSI that looks something like this:
	

	
	{% hook 'before-body-end' %}

**Comment by jellingsen** [comment]
Great. Thank you for providing us with your solution

**Comment by timmyomahony** [comment]
I'm having issues with this also.

The problem is that CSRF token used in the cookie banner will be cached by FastCGI. This means that all users on the site will be sharing the same CSRF token and therefore the POST to hide the cookie banner will return a 400. I don't think the above snippet solves that problem. 

My understanding is that SSI (used in the above example) gives _NGINX_ the ability (not PHP) to insert content into the response after fetching it from the cache and sending it back to the user. This means in this example, you can use NGINX to check if the cookie is in the response going out to the user and therefore hide the banner, but this doesn't address actually serving the correct CSRF token in the first place.

**Comment by paragonn** [comment]
I also want to follow up hear and say we are still having problems with the CSRF token and FastCGI. It would be great to have a  token that could be loaded in via javascript from an uncached URL. Here is an article about how Solspace Freeform solved the issue: https://docs.solspace.com/craft/freeform/v3/templating/caching.html#twig-template-caching

**Comment by jellingsen** [comment]
Hi, sorry for the late update on this issue!

Looking at Freeform, this should be achievable using the same technique.

Create a twig file with the current content (as Freeform, i assume this called `dynamic.twig` and is located in template root)
```
{{ {
    csrf: {
        name: craft.app.config.general.csrfTokenName,
        value: craft.app.request.csrfToken,
    }
}|json_encode|raw }}
```
Then add the following JS snippet below the cookie consent banner template:

```
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script>
    $(function () {
        let form = document.querySelector('#elc-cookie-consent-form');
        $.ajax({
            url: '/dynamic',
            type: 'get',
            dataType: 'json',
            success: function (response) {
                let csrf = response.csrf;
                form.querySelector('input[name=' + csrf.name + ']').value = csrf.value;
            },
        });
    });
</script>
```
If you want, you can copy the banner template into your own template folder and update the site settings accordingly. You can then add the javascript right under the markup so that it does not load unless the cookie consent banner loads.

I will update the README in the next release.

I hope this solves your issues.
